SQL_FILE_NAME = "player_inv.db"

STATTRACK = "StatTrak™"
STAR = "★"
STEAM_PRICE_KEY = "lowest_price"

SQL_INVENTORY_TABLE_NAME = "INVENTORY"
SQL_INVENTORY_INDEX = "ID"
SQL_INVENTORY_INDEX_VAR = "INTEGER"
SQL_INVENTORY_ITEM_NAME = "ITEM_NAME"
SQL_INVENTORY_ITEM_NAME_VAR = "TEXT"
SQL_INVENTORY_ITEM_TYPE = "ITEM_TYPE"
SQL_INVENTORY_ITEM_TYPE_VAR = "TEXT"
SQL_INVENTORY_CONDITION = "CONDITION"
SQL_INVENTORY_CONDITION_VAR = "TEXT"
SQL_INVENTORY_USERNAME = "USERNAME"
SQL_INVENTORY_USERNAME_VAR = "TEXT"
SQL_INVENTORY_STATTRACK = "STATRACK"
SQL_INVENTORY_STATTRACK_VAR = "BOOL"

SQL_PURCHASE_HISTORY_TABLE_NAME = "PURCHASE_HISTORY"
SQL_PURCHASE_HISTORY_ID = "ID"
SQL_PURCHASE_HISTORY_ID_VAR = "INTEGER"
SQL_PURCHASE_HISTORY_DATE = "DATE"
SQL_PURCHASE_HISTORY_DATE_VAR = "TEXT"
SQL_PURCHASE_HISTORY_PRICE = "PRICE"
SQL_PURCHASE_HISTORY_PRICE_VAR = "INTEGER"
SQL_PURCHASE_HISTORY_FOREIGN_INVENTORY_ID = "INVENTORY_ID"

COUNTRY_KEY = 'country'
COUNTRY_VALUE = "US"
CURRENCY_KEY = 'currency'
CURRENCY_VALUE = 1
APPID_KEY = "appid"
COUNTER_STRIKE_APP_ID = 730
MARKET_HASH_KEY = "market_hash_name"
START_KEY = "start"
START_VALUE = 0
COUNT_KEY = "count"
COUNT_VALUE = 1
LANGUAGE_KEY = "l"
LANGUAGE_VALUE = "english"
QUERY_SEARCH_KEY = "q"

STEAM_MARKET_BASE_URL = "https://steamcommunity.com/market/priceoverview"
STEAM_MARKET_SEARCH_URL = "https://steamcommunity.com/market/search"
STEAM_SEARCH_URL = "search"
STEAM_LIST_URL = "listings"

CS_UNIQUE_ITEMS = ["Case", "Pin", "Knife", "Key", "Pass"] #these items do not follow the standard str format